version: '3.9'

services:
  bizmate-backend:
    build: ./Server
    container_name: bizmate-backend
    restart: always
    environment:
      PORT: 4040
    ports:
      - "4040:4040"
    networks:
      - bizmate-net

  bizmate-frontend:
    build: ./Client
    container_name: bizmate-frontend
    restart: always
    environment:
      PORT: 3000
    depends_on:
      - bizmate-backend
    ports:
      - "3001:3000"
    networks:
      - bizmate-net

networks:
  bizmate-net:
    driver: bridge
