import { FormField } from "../interfaces/formField";

export const documentConfigs: Record<
  string,
  { title: string; description: string; fields: FormField[] }
> = {
  nda: {
    title: "Non-Disclosure Agreement",
    description:
      "Create a legally binding NDA to protect confidential information",
    fields: [
      {
        id: "disclosingParty",
        label: "Disclosing Party Name",
        type: "text",
        required: true,
        placeholder: "Your Company Name",
        aiSuggestion: "Auto-filled from profile",
      },
      {
        id: "disclosingPartyAddress",
        label: "Disclosing Party Address",
        type: "textarea",
        required: true,
        placeholder: "Complete business address",
      },
      {
        id: "receivingParty",
        label: "Receiving Party Name",
        type: "text",
        required: true,
        placeholder: "Client/Partner Name",
      },
      {
        id: "receivingPartyAddress",
        label: "Receiving Party Address",
        type: "textarea",
        required: true,
        placeholder: "Client/Partner address",
      },
      {
        id: "effectiveDate",
        label: "Effective Date",
        type: "date",
        required: true,
      },
      {
        id: "duration",
        label: "Agreement Duration",
        type: "select",
        required: true,
        options: ["1 Year", "2 Years", "3 Years", "5 Years", "Indefinite"],
      },
      {
        id: "purpose",
        label: "Purpose of Disclosure",
        type: "textarea",
        required: true,
        placeholder: "Describe the business purpose...",
        helpText: "Be specific about why information is being shared",
      },
      {
        id: "jurisdiction",
        label: "Governing Law",
        type: "select",
        required: true,
        options: ["UAE - Dubai", "UAE - Abu Dhabi", "UAE - DIFC", "UAE - ADGM"],
      },
    ],
  },
  "employment-contract": {
    title: "Employment Contract",
    description: "Generate UAE labor law compliant employment agreements",
    fields: [
      {
        id: "employerName",
        label: "Employer Name",
        type: "text",
        required: true,
        aiSuggestion: "Auto-filled from profile",
      },
      {
        id: "employerLicense",
        label: "Trade License Number",
        type: "text",
        required: true,
        aiSuggestion: "Auto-filled from profile",
      },
      {
        id: "employeeName",
        label: "Employee Full Name",
        type: "text",
        required: true,
        placeholder: "As per Emirates ID",
      },
      {
        id: "employeePassport",
        label: "Passport Number",
        type: "text",
        required: true,
      },
      {
        id: "position",
        label: "Job Position",
        type: "text",
        required: true,
        placeholder: "e.g., Senior Software Engineer",
      },
      {
        id: "salary",
        label: "Monthly Salary (AED)",
        type: "number",
        required: true,
        placeholder: "15000",
      },
      { id: "startDate", label: "Start Date", type: "date", required: true },
      {
        id: "contractType",
        label: "Contract Type",
        type: "select",
        required: true,
        options: ["Limited Term (2 Years)", "Unlimited Term"],
      },
      {
        id: "probationPeriod",
        label: "Probation Period",
        type: "select",
        required: true,
        options: ["3 Months", "6 Months", "No Probation"],
      },
      {
        id: "benefits",
        label: "Additional Benefits",
        type: "textarea",
        required: false,
        placeholder: "Housing allowance, medical insurance, etc.",
      },
    ],
  },
  invoice: {
    title: "VAT Invoice",
    description: "Create professional invoices with automatic VAT calculation",
    fields: [
      {
        id: "invoiceNumber",
        label: "Invoice Number",
        type: "text",
        required: true,
        aiSuggestion: "Auto-generated: INV-2024-0157",
      },
      {
        id: "invoiceDate",
        label: "Invoice Date",
        type: "date",
        required: true,
      },
      { id: "dueDate", label: "Due Date", type: "date", required: true },
      {
        id: "clientName",
        label: "Client Name",
        type: "text",
        required: true,
        placeholder: "Client/Company Name",
      },
      {
        id: "clientAddress",
        label: "Client Address",
        type: "textarea",
        required: true,
      },
      {
        id: "clientTRN",
        label: "Client TRN (Optional)",
        type: "text",
        required: false,
        placeholder: "Tax Registration Number",
      },
      {
        id: "description",
        label: "Service/Product Description",
        type: "textarea",
        required: true,
        placeholder: "Describe items or services...",
      },
      {
        id: "amount",
        label: "Amount (AED)",
        type: "number",
        required: true,
        placeholder: "10000",
      },
      {
        id: "vatRate",
        label: "VAT Rate",
        type: "select",
        required: true,
        options: ["5% Standard", "0% Zero-Rated", "Exempt"],
      },
      {
        id: "paymentTerms",
        label: "Payment Terms",
        type: "textarea",
        required: false,
        placeholder: "Bank transfer details, payment method...",
      },
    ],
  },
  "service-agreement": {
    title: "Service Agreement",
    description: "Professional service contracts tailored to your needs",
    fields: [
      {
        id: "serviceProvider",
        label: "Service Provider",
        type: "text",
        required: true,
        aiSuggestion: "Auto-filled from profile",
      },
      { id: "client", label: "Client Name", type: "text", required: true },
      {
        id: "serviceDescription",
        label: "Services to be Provided",
        type: "textarea",
        required: true,
        placeholder: "Detailed description of services...",
      },
      {
        id: "contractValue",
        label: "Contract Value (AED)",
        type: "number",
        required: true,
      },
      { id: "startDate", label: "Start Date", type: "date", required: true },
      { id: "endDate", label: "End Date", type: "date", required: true },
      {
        id: "paymentSchedule",
        label: "Payment Schedule",
        type: "select",
        required: true,
        options: ["Monthly", "Quarterly", "Milestone-based", "Upon Completion"],
      },
      {
        id: "termination",
        label: "Termination Notice Period",
        type: "select",
        required: true,
        options: ["30 Days", "60 Days", "90 Days"],
      },
    ],
  },
  "offer-letter": {
    title: "Job Offer Letter",
    description: "Professional offer letters with UAE employment standards",
    fields: [
      {
        id: "companyName",
        label: "Company Name",
        type: "text",
        required: true,
        aiSuggestion: "Auto-filled from profile",
      },
      {
        id: "candidateName",
        label: "Candidate Name",
        type: "text",
        required: true,
      },
      {
        id: "position",
        label: "Position Title",
        type: "text",
        required: true,
      },
      { id: "department", label: "Department", type: "text", required: true },
      {
        id: "salary",
        label: "Annual Salary (AED)",
        type: "number",
        required: true,
      },
      {
        id: "startDate",
        label: "Proposed Start Date",
        type: "date",
        required: true,
      },
      {
        id: "reportingTo",
        label: "Reporting To",
        type: "text",
        required: true,
      },
      {
        id: "benefits",
        label: "Benefits Package",
        type: "textarea",
        required: true,
      },
      {
        id: "acceptanceDeadline",
        label: "Offer Valid Until",
        type: "date",
        required: true,
      },
    ],
  },
  "termination-letter": {
    title: "Employment Termination Letter",
    description: "UAE labor law compliant termination letters",
    fields: [
      {
        id: "employeeName",
        label: "Employee Name",
        type: "text",
        required: true,
      },
      {
        id: "employeeId",
        label: "Employee ID",
        type: "text",
        required: true,
      },
      { id: "position", label: "Position", type: "text", required: true },
      {
        id: "terminationType",
        label: "Termination Type",
        type: "select",
        required: true,
        options: [
          "Resignation",
          "Termination with Cause",
          "Termination without Cause",
          "Contract Expiry",
        ],
      },
      {
        id: "terminationDate",
        label: "Last Working Day",
        type: "date",
        required: true,
      },
      {
        id: "reason",
        label: "Reason (if applicable)",
        type: "textarea",
        required: false,
      },
      {
        id: "noticePeriod",
        label: "Notice Period Served",
        type: "select",
        required: true,
        options: ["30 Days", "60 Days", "90 Days", "Immediate"],
      },
      {
        id: "finalSettlement",
        label: "Final Settlement Details",
        type: "textarea",
        required: true,
        placeholder: "End of service benefits, pending salary, etc.",
      },
    ],
  },
};
