// src/documents/documents.entity.ts
// NEW ENTITY — stores every document generated by a user (from template or AI).
// This is separate from document_history (which handles uploaded/compliance files).

import {
  Entity,
  Column,
  PrimaryColumn,
  CreateDateColumn,
  UpdateDateColumn,
} from "typeorm";

/**
 * Full lifecycle a generated document moves through.
 * Draft → AI Generated → Under Review → Approved → Finalised → Archived
 */
export enum DocumentStatus {
  DRAFT       = "draft",
  AI_GENERATED = "ai_generated",
  UNDER_REVIEW = "under_review",
  APPROVED    = "approved",
  FINALISED   = "finalised",
  ARCHIVED    = "archived",
}

/** Where the document came from */
export enum DocumentSource {
  TEMPLATE = "template",   // User filled a prebuilt template form
  AI       = "ai",         // AI generated from a natural language prompt
  CUSTOM   = "custom",     // User-created custom template
}

@Entity("generated_documents")
export class GeneratedDocumentEntity {

  @PrimaryColumn({
    type: "uuid",
    default: () => "gen_random_uuid()",
    unique: true,
  })
  uuid!: string;

  @Column({ type: "integer", generated: "increment" })
  id!: number;

  // Who owns this document
  @Column({ type: "uuid", nullable: false })
  user_id!: string;

  // Which template was used (null for pure AI documents)
  @Column({ type: "uuid", nullable: true, default: null })
  template_id!: string | null;

  // Human-readable document name (e.g. "NDA — Tech Solutions LLC")
  @Column({ type: "varchar", length: 255, nullable: false })
  document_name!: string;

  // Document category for filtering (e.g. "Legal", "HR", "Finance")
  @Column({ type: "varchar", length: 100, nullable: true, default: null })
  category!: string;

  // Template or document type label (e.g. "NDA", "Employment Contract")
  @Column({ type: "varchar", length: 100, nullable: true, default: null })
  document_type!: string;

  // All the filled-in field values as a key-value JSON object
  @Column({ type: "jsonb", default: () => "'{}'" })
  field_values!: Record<string, any>;

  // Full generated document content (HTML or plain text — rendered for PDF/DOCX)
  @Column({ type: "text", nullable: true, default: null })
  content!: string;

  // The original prompt used if this was AI generated
  @Column({ type: "text", nullable: true, default: null })
  ai_prompt!: string;

  // AI compliance score 0–100
  @Column({ type: "integer", nullable: true, default: null })
  compliance_score!: number | null;

  // AI compliance notes — array of { type: "ok"|"warning"|"error", message: string }
  @Column({ type: "jsonb", default: () => "'[]'" })
  compliance_notes!: { type: string; message: string }[];

  // Status lifecycle
  @Column({
    type: "varchar",
    length: 50,
    default: DocumentStatus.DRAFT,
  })
  status!: DocumentStatus;

  // Source (template / ai / custom)
  @Column({
    type: "varchar",
    length: 50,
    default: DocumentSource.TEMPLATE,
  })
  source!: DocumentSource;

  // Activity log — every status transition timestamped
  @Column({ type: "jsonb", default: () => "'[]'" })
  activity_log!: { status: string; timestamp: string }[];

  // Saved PDF path on server (populated after PDF is generated)
  @Column({ type: "varchar", length: 500, nullable: true, default: null })
  pdf_path!: string | null;

  // Saved DOCX path on server (populated after DOCX is generated)
  @Column({ type: "varchar", length: 500, nullable: true, default: null })
  docx_path!: string | null;

  @CreateDateColumn({ type: "timestamp", default: () => "CURRENT_TIMESTAMP" })
  created_at!: Date;

  @UpdateDateColumn({ type: "timestamp", default: () => "CURRENT_TIMESTAMP" })
  updated_at!: Date;
}
