CREATE TABLE ai_reply_hub_chats (
    id SERIAL PRIMARY KEY,
    uuid UUID DEFAULT gen_random_uuid() UNIQUE,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    client_id UUID NOT NULL REFERENCES client_lists(uuid) ON DELETE CASCADE,
    platform VARCHAR(20) CHECK (platform IN ('whatsapp','email','instagram')) NOT NULL,
    direction VARCHAR(20) CHECK (direction IN ('inbound','outbound')) NOT NULL,
    message TEXT NOT NULL,
    ai_reply TEXT,
    ai_reply_enable BOOLEAN DEFAULT true,
    ai_model VARCHAR(50),  -- GPT-4, GPT-3.5, local model, etc.
    sent_at TIMESTAMP DEFAULT now(),
    received_at TIMESTAMP, -- timestamp of inbound messages
    status VARCHAR(20) CHECK (status IN ('sent','delivered','read','failed')) DEFAULT 'sent',
    error_message TEXT
);
CREATE TABLE client_lists (
    id SERIAL PRIMARY KEY,
    uuid UUID DEFAULT gen_random_uuid() UNIQUE,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name VARCHAR(255),
    email VARCHAR(255),
    whatsapp_number VARCHAR(50),
    instagram_id VARCHAR(255),
    notes TEXT,
    added_at TIMESTAMP DEFAULT now(),
    UNIQUE(user_id, email),
    UNIQUE(user_id, whatsapp_number),
    UNIQUE(user_id, instagram_id)
);
{
  "name": "John Doe",
  "email": "john.doe@gmail.com",
  "whatsapp_number": "+12025550123",
  "instagram_id": "john_doe_insta",
  "notes": "Potential premium client. Contact via WhatsApp first."
}

CREATE TABLE user_integrations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    platform VARCHAR(20) CHECK (platform IN ('email', 'whatsapp', 'instagram')) NOT NULL,
    access_token TEXT,
    refresh_token TEXT,
    expires_at TIMESTAMP,
    last_sync_at TIMESTAMP,
    status enum("connected","disconnected","",""),
    metadata JSONB,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);
 
CREATE TABLE user_business_info (
    id SERIAL PRIMARY KEY,
    uuid UUID DEFAULT gen_random_uuid() UNIQUE,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    business_name VARCHAR(150) NOT NULL,
    owner_name VARCHAR(150),
    industry VARCHAR(100) NOT NULL,
    business_type VARCHAR(50),
    services_offered TEXT NOT NULL, -- comma separated, AI converts internally to array
    communication_channels JSONB DEFAULT '["Email","WhatsApp","Instagram"]',
    availability TEXT,
    faq JSONB,                -- auto-generated by AI
    tone_examples JSONB,      -- auto-generated by AI
    snapshot JSONB,           -- full AI-processed object
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

 {
  "user_id": "u123",
  "business_type": "freelancer",
  "business_name": "Hasan Khan Design Studio",
  "description": "Freelance UI/UX designer specializing in SaaS products.",
  "services_offered": ["UI/UX Design", "Web Design"],
  "skills": ["Figma", "React", "Tailwind"],
  "industry": "Design",
  "location": "Dhaka, Bangladesh",
  "website": "https://hasankhan.design",
  "social_links": { "linkedin": "https://linkedin.com/in/hasan" },
  "team_size": 1
}

